language: node_js

sudo: true

node_js:
  - 6
  - 5

script: npm run build

install:
  - npm i -g npm@latest
  - npm install

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://raw.githubusercontent.com/rpiml/okcollege-dev/master/assets/form.json -P ./assets
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
